title: Ariel Gil - AI Safety Researcher
description: AI Safety Researcher focusing on AI Risk management, standards and policy.
url: https://ariel-gil.github.io
baseurl: ""

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - link_preview_generator
  - link_preview_helper
  - pdf_preview_generator

# Enable link previews
link_previews: true

# Enable PDF previews
pdf_previews: true

# Disable caching for testing
cache: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .github
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - _site
  - .git
  - .gitignore

